### ISSUE TITLE
DEV: Add linter for import ordering

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#94]
[Using isort with pre-commit](https://pycqa.github.io/isort/docs/configuration/pre-commit.html)

```yaml
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
        name: isort (python)
```
